//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoNAtencion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLEADO
    {
        public int ID_EMPLEADO { get; set; }
        public Nullable<int> ID_CARGO { get; set; }
        public int ID_SUCURSAL { get; set; }
        public string NOMBRE_EMPLEADO { get; set; }
        public string APPAT_EMPLEADO { get; set; }
        public string APMAT_EMPLEADO { get; set; }
        public string RUT_EMPLEADO { get; set; }
        public string DIRECCION_EMPLEADO { get; set; }
        public int TELEFONO_EMPLEADO { get; set; }
        public string EMAIL_EMPLEADO { get; set; }
        public string USUARIO_EMPLEADO { get; set; }
        public string PASS_EMPLEADO { get; set; }
        public int UCR_EMPLEADO { get; set; }
        public Nullable<int> UAC_EMPLEADO { get; set; }
        public Nullable<int> UEL_EMPLEADO { get; set; }
        public System.DateTime FCR_EMPLEADO { get; set; }
        public Nullable<System.DateTime> FAC_EMPLEADO { get; set; }
        public Nullable<System.DateTime> FEL_EMPLEADO { get; set; }
    
        public virtual CARGO CARGO { get; set; }
        public virtual SUCURSAL SUCURSAL { get; set; }
    }
}
