//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoNAtencion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPRESA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EMPRESA()
        {
            this.SUCURSAL = new HashSet<SUCURSAL>();
        }
    
        public int ID_EMPRESA { get; set; }
        public Nullable<int> ID_COMUNA { get; set; }
        public string NOMBRE_EMPRESA { get; set; }
        public string RUT_EMPRESA { get; set; }
        public string DIRECCION_EMPRESA { get; set; }
        public string RUBRO_EMPRESA { get; set; }
        public string GIRO_EMPRESA { get; set; }
        public int UCR_EMPRESA { get; set; }
        public Nullable<int> CAC_EMPRESA { get; set; }
        public Nullable<int> UEL_EMPRESA { get; set; }
        public System.DateTime FCR_EMPRESA { get; set; }
        public Nullable<System.DateTime> FAC_EMPRESA { get; set; }
        public Nullable<System.DateTime> FEL_EMPRESA { get; set; }
    
        public virtual COMUNA COMUNA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SUCURSAL> SUCURSAL { get; set; }
    }
}
