//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoNAtencion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRIVILEGIO
    {
        public int ID_PRIVILEGIO { get; set; }
        public Nullable<int> ID_ROL { get; set; }
        public string NOMBRE_PRIVILEGIO { get; set; }
        public string DESCRIPCION_PRIVILEGIO { get; set; }
    
        public virtual ROL ROL { get; set; }
    }
}
