//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Natencion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CLIENTE()
        {
            this.RESERVA = new HashSet<RESERVA>();
        }
    
        public int ID_CLIENTE { get; set; }
        public Nullable<int> ID_ESTADO { get; set; }
        public Nullable<int> ID_ROL { get; set; }
        public string NOMBRE { get; set; }
        public string APPAT { get; set; }
        public string APMAT { get; set; }
        public string RUT { get; set; }
        public string DIRECCION { get; set; }
        public int TELEFONO { get; set; }
        public string EMAIL { get; set; }
        public string USUARIO { get; set; }
        public string PASS { get; set; }
        public string PREGUNTASEG1 { get; set; }
        public string RESPUESTASEG1 { get; set; }
        public string PREGUNTASEG2 { get; set; }
        public string RESPUESTASEG2 { get; set; }
        public Nullable<int> UCR_CLIENTE { get; set; }
        public Nullable<int> UAC_CLIENTE { get; set; }
        public Nullable<int> UEL_CLIENTE { get; set; }
        public Nullable<System.DateTime> FCR_CLIENTE { get; set; }
        public Nullable<System.DateTime> FAC_CLIENTE { get; set; }
        public Nullable<System.DateTime> FEL_CLIENTE { get; set; }
    
        public virtual ESTADO ESTADO { get; set; }
        public virtual ROL ROL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RESERVA> RESERVA { get; set; }
    }
}
