//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Natencion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUCURSAL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SUCURSAL()
        {
            this.EMPLEADO = new HashSet<EMPLEADO>();
            this.RESERVA = new HashSet<RESERVA>();
        }
    
        public int ID_SUCURSAL { get; set; }
        public Nullable<int> ID_CLASIFICACION { get; set; }
        public Nullable<int> ID_EMPRESA { get; set; }
        public string NOMBRE_SUCURSAL { get; set; }
        public System.TimeSpan HORA_INICIO { get; set; }
        public System.TimeSpan HORA_TERMINO { get; set; }
        public decimal LATITUD_SUCURSAL { get; set; }
        public decimal LONGITUD_SUCURSAL { get; set; }
        public decimal PRECISION_SUCURSAL { get; set; }
        public int UCR_SUCURSAL { get; set; }
        public Nullable<int> UAC_SUCURSAL { get; set; }
        public Nullable<int> UEL_SUCURSAL { get; set; }
        public System.DateTime FCR_SUCURSAL { get; set; }
        public Nullable<System.DateTime> FAC_SUCURSAL { get; set; }
        public Nullable<System.DateTime> FEL_SUCURSAL { get; set; }
    
        public virtual CLASIFICACION CLASIFICACION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMPLEADO> EMPLEADO { get; set; }
        public virtual EMPRESA EMPRESA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RESERVA> RESERVA { get; set; }
    }
}
